language: node_js
node_js:
  - "8.9.4"
python:
  - "3.6"
install:
  - pip install vyper
  - npm install
  - npm link
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage