language:
- node_js:
before_install:
  - npm install -g lerna
  - npm install -g nyc
  - npm install -g codecov
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - npm install
  - lerna bootstrap
  - cd packages/etherlime
  - yarn link
  - cd ../..
services:
  - docker
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage